spring:
  boot:
    admin:
      client:
        url: http://192.168.1.116:8084
  application:
    name: cwj-itoken-zipkin
server:
  port: 9411


eureka:
  client:
    serviceUrl:
      #defaultZone: http://192.168.116:8761/eureka/,http://192.168.116:8761/eureka/,http://192.168.116:8761/eureka/
      defaultZone:http://192.168.1.116:8761/eureka/,http://192.168.1.116:8861/eureka/,http://192.168.1.116:8961/eureka/

#management:
#  metrics:
#    web:
#      server:
#        auto-time-requests: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info