spring:
  boot:
    admin:
      client:
        url: http://localhost:8084
  application:
    name: cwj-itoken-eureka
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#spring-cloud-admin健康检查
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info